### PR TITLE
Plugin Improvements

### PR DESCRIPTION
**Pull request by bassplayer7**
I've been working on making some improvements to the plugin - especially not that we have more access to the admin panel. It ended up being more comprehensive than I originally was picturing, but I think it is much better as a result. 

---
#### Upgrades:
- Moved nearly all of the controls to the admin panel. The contact can be enabled per-page.
- Refactored the modular functionality of the plugin so that it will work seamlessly with modular pages instead of needing a template change.
- Prefered the Grav Email plugin first if it is available, and if not, falling back to the default `mail()`.
- Removed unnecessary jQuery dependency. (Which required it to be loaded in the head, which isn't cool.)
- Changed to display messages from the session instead of redirecting.
- Save form values to the session for convenience as well. 
- Added improved class names so end-users can more easily style the segments.
- Introduced a bit of a fallback for the email recipient. 

---
#### Bug Fixes:
- Fixed a bug which caused the CSS to not load on modular pages.
- Fixed a problem which caused the form to shrink at 50% of the screen width to an uncomfortable width.

### CODE REVIEW

**Comment by bassplayer7** [comment]
@Perlkonig I opened this PR as I am interested in getting your input. If you have the opportunity to test this branch as well, that would be great. I'm still working on testing it as I have time, but think it is getting pretty close.

I'm also wondering about bumping the version to v2 before merging this? My goal is 100% backwards compatibility, but it may not end up being that depending on how some users may have integrated with it.

**Comment by Perlkonig** [comment]
It may not be until the weekend before I can test, but I will. Thanks!

**Comment by bassplayer7** [comment]
That's just fine. Thank you. I'll try to finish my part of the testing by then. If you want to and are familiar with PHP, feel free to review and make suggestions on the code as well. I'm always open to ideas. Before merging this, I want to work on the README as well to make it more approachable.

**Comment by Perlkonig** [comment]
Sorry for the delay. Looks good to me. I have no problem with a version bump. And any work we can do on the README would be great. I just did an initial cleaning pass, but with the new changes, let's see what we can do.

**Review by Perlkonig — APPROVED** [review]
Looks fine to me, but I'm not a PHP native. It's not like we can't fix things later if necessary.

**Comment by bassplayer7** [comment]
Thanks for looking it over @Perlkonig. I'll try to get a few more minutes to wrap my part up and then I'll merge it.

**Pull request merged**
