### PR TITLE
Changes to make customizing the CSS easier

### PR DESCRIPTION
**Pull request by Perlkonig**
- Moved and renamed the CSS file to the base `assets` folder.
- Updated the PHP file to look in the active theme's `assets` folder for the override if `disable_css` is `true`.
- Updated the README to explain how to customize.

### CODE REVIEW

**Comment by Perlkonig** [comment]
I see there are a number pull requests. I'm happy to help with the maintenance, if you want to grant a couple of us write access. Thanks!

**Comment by aradianoff** [comment]
Sorry for the delay. I have been away for a long time and will probably be offline for a couple of months more due to personal reasons. I am giving you and bassplayer7 (he made lots of changes in the code) write access to the repository so that you can  maintain and improve the plugin as you see fit during this time. Thanks.

**Comment by Perlkonig** [comment]
Cheers! Be well.

**Comment by bassplayer7** [comment]
@aradianoff, thanks for bringing us onto the repo and I look forward to keeping this plugin available to those who want to use it.

**Pull request merged**
