### PR TITLE
Release prep

### PR DESCRIPTION
**Pull request by Perlkonig**
Updated the `blueprints.yaml` and `CHANGELOG.md` files in preparation for generating a v1.0.9 release. Did I miss something in the CHANGELOG?

### CODE REVIEW

**Comment by Perlkonig** [comment]
Oops. I didn't branch properly, so the README changes are also here. Sorry!

**Comment by Perlkonig** [comment]
I'm reasonably sure the CHANGELOG is correct. If I don't hear from you, @aradianoff, by tomorrow, I'll go ahead and produce the new release.

**Comment by Perlkonig** [comment]
Going to release. We can fix anything I missed afterwards. Thanks!

**Comment by bassplayer7** [comment]
@Perlkonig thanks for your work on this. Feel free to ping me as well if you have specific questions - especially regarding code.

**Comment by Perlkonig** [comment]
Sorry, @bassplayer7 ! I meant to at _you_ but accidentally pinged @aradianoff! Sorry to both of you. My bad :)

**Comment by bassplayer7** [comment]
No problem at all. Thanks.

**Pull request merged**
